[package]
name = "sdk_example_actor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fvm_rs_sdk = { version = "0.0.1", path = "../../sdk" }

[build-dependencies]
wasm-builder = "3.0.1"